name: DDLReminder
on:
  workflow_dispatch:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 45 */12 * * *

jobs:
  HomeworkCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.8.14'
    - name: 'Install dependencies'
      run: python3 -m pip install --upgrade pip

    - name: 'install libs'
      run: pip3 install requests 

    - name: StratCheckHomework
      env:
        ZJU_USERNAME: ${{ secrets.ZJU_USERNAME }}
        ZJU_PASSWORD: ${{ secrets.ZJU_PASSWORD }}

        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}

      run: python3 getDDLContent.py
